### ISSUE TITLE
Tracking issue foundryup features

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundryup#1]
Some thoughts on tasks:

**Meta**

- [ ] We need to settle on a manifest format that (1) supports release channels (stable, nightly), (2) is semver compatible (even for nightly versions), (3) maybe supports installing singular components (e.g. only Forge, only Anvil or a combination), (4) support multiple targets (e.g. linux arm, linux x86, mac m1, mac x86, ...)
- [ ] We need a place to store this information (S3?)
- [ ] We need to update the release script to upload manifests to the target described above, and the release script should also build Foundryup
- [x] We need to figure out if we can start building for Windows again
- [ ] We need to add relevant issues to Foundry Book
  - [ ] Update installation instructions
  - [ ] Foundryup reference

**Install**

- [ ] Install from git
  - [ ] Support branches
  - [ ] Support commits
  - [ ] Support git repos
  - [ ] Maybe we should also port `foundryup --pr`?
- [ ] Install from directory
- [ ] Install from manifest
  - [ ] Install latest by channel name (e.g. nightly, stable)
  - [ ] Install specific version

**Update**

- [ ] A way to specify the default channel (stable, nightly)
- [ ] Update will always update from the default channel
- [ ] Self-updating

**Misc**

- [ ] Support for XDG base directory specification https://github.com/foundry-rs/foundry/issues/1262

**Questions**

- Should we support multiple versions of components? I can imagine that it might be beneficial to run some projects in the future with a specific Forge version, and others with the latest one, perhaps because of a breaking change. If so, we should have a toolchain-like concept like rustup as well

_Originally posted by @onbjerg in https://github.com/foundry-rs/foundry/issues/1647#issuecomment-1131958235_
